### ISSUE TITLE
implement quota/capacity on nodes

### ISSUE THREAD

**Issue by fsouza** [tsuru/docker-cluster#16]
Each node will have a quota of "available" containers. Whenever the cluster runs out of containers, it should fail to create new containers.

**Comment by derit** [comment]
@fsouza i think this project was done?

**Comment by derit** [comment]
look at kubernetes, kubernetes implement with cpuset using cgroup

**Comment by fsouza** [comment]
@derit not sure if this is completely done, it's certainly in maintenance mode, but I no longer work on it. 

This issue is 7 years old though, so I'm not sure what you mean. Are you asking to close it?

**Comment by derit** [comment]
yes sure
